/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form1;

/**
 *
 * @author ACER
 */
public class DescFilm4 extends javax.swing.JFrame {

    /**
     * Creates new form DescFilm4
     */
    public DescFilm4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_icon = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Sinopsis = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_review = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Dsc1_dscrptn = new javax.swing.JLabel();
        Dsc1_Directors = new javax.swing.JLabel();
        Dsc1_Writers = new javax.swing.JLabel();
        Dsc1_Stars = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tbl_kembali = new javax.swing.JButton();
        lbl_rtg = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\study.png")); // NOI18N
        jLabel1.setText("Sinopsis");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\script.png")); // NOI18N
        jLabel2.setText("Review");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        lbl_icon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_icon.setForeground(new java.awt.Color(255, 255, 255));
        lbl_icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Pictures\\Joker.jpg")); // NOI18N
        lbl_icon.setText("    JOKER");
        getContentPane().add(lbl_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 180, -1));

        jScrollPane2.setBackground(new java.awt.Color(0, 102, 51));
        jScrollPane2.setForeground(new java.awt.Color(204, 204, 0));

        txt_Sinopsis.setEditable(false);
        txt_Sinopsis.setColumns(20);
        txt_Sinopsis.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        txt_Sinopsis.setForeground(new java.awt.Color(102, 102, 102));
        txt_Sinopsis.setRows(5);
        txt_Sinopsis.setText("Kisah asli Joker yang belum pernah ada sebelumnya di layar lebar.");
        txt_Sinopsis.setOpaque(false);
        txt_Sinopsis.setSelectionColor(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(txt_Sinopsis);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 196, 510, 50));

        txt_review.setEditable(false);
        txt_review.setColumns(20);
        txt_review.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        txt_review.setForeground(new java.awt.Color(102, 102, 102));
        txt_review.setRows(5);
        txt_review.setText("Menampilkan kinerja yang memukau, dengan penuh penghayatan, dan yang kandidat layak-Oscar oleh Joaquin Phoenix, \nJoker bekerja dengan sangat baik dengan studi karakter yang mengasyikkan tanpa ada jebakan DC Comics; \nbahwa kebetulan film Batman-universe yang brilian sedang populer di Batfan Cake. Anda mungkin akan merasakan\nperasaan hebat setelah menonton Joker seperti yang saya rasakan: \ngelisah dan siap untuk berdebat tentang film selama bertahun-tahun yang akan datang.");
        txt_review.setOpaque(false);
        jScrollPane1.setViewportView(txt_review);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 295, 790, 90));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel5.setText("Cinema");

        jLabel6.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Big Shot  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 240, -1));

        Dsc1_dscrptn.setForeground(new java.awt.Color(255, 255, 255));
        Dsc1_dscrptn.setText("R | 2h 2min | Crime, Drama, Thriller ");
        getContentPane().add(Dsc1_dscrptn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        Dsc1_Directors.setForeground(new java.awt.Color(255, 255, 255));
        Dsc1_Directors.setText("Director: Todd Phillips");
        getContentPane().add(Dsc1_Directors, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        Dsc1_Writers.setForeground(new java.awt.Color(255, 255, 255));
        Dsc1_Writers.setText("Writers: Todd Phillips, Scott Silver | 3 more credits");
        getContentPane().add(Dsc1_Writers, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        Dsc1_Stars.setForeground(new java.awt.Color(255, 255, 255));
        Dsc1_Stars.setText("Stars: Joaquin Phoenix, Robert De Niro, Zazie Beetz");
        getContentPane().add(Dsc1_Stars, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("DC Films.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 30, 110, -1));

        tbl_kembali.setBackground(new java.awt.Color(0, 0, 102));
        tbl_kembali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbl_kembali.setForeground(new java.awt.Color(255, 255, 255));
        tbl_kembali.setText("Kembali");
        tbl_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(tbl_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 110, 40));

        lbl_rtg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_rtg.setForeground(new java.awt.Color(255, 255, 255));
        lbl_rtg.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\star.png")); // NOI18N
        lbl_rtg.setText("9.0/10");
        getContentPane().add(lbl_rtg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 30));

        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Pictures\\j1.jpg")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 80));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Pictures\\j2.jpg")); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Pictures\\j3.jpg")); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 150, 80));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Pictures\\j4.jpg")); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, 80));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\FlatIcon.png")); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl_kembaliActionPerformed
        MenuUtama u= new MenuUtama();
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tbl_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DescFilm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DescFilm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DescFilm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DescFilm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DescFilm4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dsc1_Directors;
    private javax.swing.JLabel Dsc1_Stars;
    private javax.swing.JLabel Dsc1_Writers;
    private javax.swing.JLabel Dsc1_dscrptn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_rtg;
    private javax.swing.JButton tbl_kembali;
    public static javax.swing.JTextArea txt_Sinopsis;
    private javax.swing.JTextArea txt_review;
    // End of variables declaration//GEN-END:variables
}
