/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form1;

import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class Login1 extends javax.swing.JFrame {

    /**
     * Creates new form Login1
     */
    public Login1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        KlikLogout = new javax.swing.JButton();
        KlikLogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        KlikLogin1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cinema");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 170, 60));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 260, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\logout (2).png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\login (1).png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 40, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\video-camera.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 50, 40));

        KlikLogout.setBackground(new java.awt.Color(153, 153, 255));
        KlikLogout.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        KlikLogout.setText("LOG-OUT");
        KlikLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlikLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(KlikLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 170, 80));

        KlikLogin.setBackground(new java.awt.Color(153, 153, 255));
        KlikLogin.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        KlikLogin.setText("INFO");
        KlikLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        KlikLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlikLoginActionPerformed(evt);
            }
        });
        jPanel1.add(KlikLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 170, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\cinema.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 40, 40));

        jLabel9.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Big Shot");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 300, 70));

        KlikLogin1.setBackground(new java.awt.Color(153, 153, 255));
        KlikLogin1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        KlikLogin1.setText("LOG-IN");
        KlikLogin1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        KlikLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlikLogin1ActionPerformed(evt);
            }
        });
        jPanel1.add(KlikLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 170, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\info.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 30, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\FlatIcon.png")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KlikLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlikLoginActionPerformed
        InfoPembuat i= new InfoPembuat();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KlikLoginActionPerformed

    private void KlikLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlikLogoutActionPerformed
        JOptionPane.showMessageDialog(null, " Apakah anda ingin keluar?" ,"Konfirmasi?", JOptionPane.QUESTION_MESSAGE);
        JOptionPane.showMessageDialog(null, " TERIMAKASIH "); 
        dispose();
    }//GEN-LAST:event_KlikLogoutActionPerformed

    private void KlikLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlikLogin1ActionPerformed
        MenuLogin n= new MenuLogin();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KlikLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KlikLogin;
    private javax.swing.JButton KlikLogin1;
    private javax.swing.JButton KlikLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
