/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form1;

/**
 *
 * @author ACER
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gabung = new javax.swing.ButtonGroup();
        Gabung2 = new javax.swing.ButtonGroup();
        Gabung3 = new javax.swing.ButtonGroup();
        Gabung4 = new javax.swing.ButtonGroup();
        Gabung5 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton23 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rdouangtunai = new javax.swing.JRadioButton();
        rdobca = new javax.swing.JRadioButton();
        rdobni = new javax.swing.JRadioButton();
        rdomandiri = new javax.swing.JRadioButton();
        rdobri = new javax.swing.JRadioButton();
        rdoovo = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        btnHitung = new javax.swing.JButton();
        btnKosong = new javax.swing.JButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        chkfilm1 = new javax.swing.JCheckBox();
        jRadioButton7 = new javax.swing.JRadioButton();
        chkfilm2 = new javax.swing.JCheckBox();
        lblTotal = new javax.swing.JLabel();
        chkfilm3 = new javax.swing.JCheckBox();
        chkfilm4 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblJamMenonton = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtfilm1 = new javax.swing.JTextField();
        txtfilm2 = new javax.swing.JTextField();
        jRadioButton20 = new javax.swing.JRadioButton();
        txtfilm3 = new javax.swing.JTextField();
        jRadioButton21 = new javax.swing.JRadioButton();
        txtfilm4 = new javax.swing.JTextField();
        jRadioButton22 = new javax.swing.JRadioButton();
        KlikFilm4 = new javax.swing.JButton();
        KlikFilm = new javax.swing.JButton();
        KlikFilm2 = new javax.swing.JButton();
        KlikFilm3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblCaraBayar1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel4.setText("TIKET");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jRadioButton23.setBackground(new java.awt.Color(102, 102, 102));
        Gabung.add(jRadioButton23);
        jRadioButton23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton23.setText("21:00");
        jRadioButton23.setOpaque(false);
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 170, 70, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("METODE PEMBAYARAN");

        rdouangtunai.setBackground(new java.awt.Color(102, 102, 102));
        Gabung5.add(rdouangtunai);
        rdouangtunai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdouangtunai.setText("Uang Tunai");
        rdouangtunai.setOpaque(false);
        rdouangtunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdouangtunaiActionPerformed(evt);
            }
        });

        rdobca.setBackground(new java.awt.Color(102, 102, 102));
        Gabung5.add(rdobca);
        rdobca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdobca.setText("Debit BCA");
        rdobca.setOpaque(false);

        rdobni.setBackground(new java.awt.Color(102, 102, 102));
        Gabung5.add(rdobni);
        rdobni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdobni.setText("Debit BNI");
        rdobni.setOpaque(false);

        rdomandiri.setBackground(new java.awt.Color(102, 102, 102));
        Gabung5.add(rdomandiri);
        rdomandiri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdomandiri.setText("Debit MANDIRI");
        rdomandiri.setOpaque(false);
        rdomandiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdomandiriActionPerformed(evt);
            }
        });

        rdobri.setBackground(new java.awt.Color(102, 102, 102));
        Gabung5.add(rdobri);
        rdobri.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdobri.setText("Debit BRI");
        rdobri.setOpaque(false);

        rdoovo.setBackground(new java.awt.Color(102, 102, 102));
        Gabung5.add(rdoovo);
        rdoovo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoovo.setText("OVO");
        rdoovo.setOpaque(false);
        rdoovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdomandiri)
                            .addComponent(rdouangtunai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdobca)
                            .addComponent(rdobri))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdobni)
                            .addComponent(rdoovo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdouangtunai)
                    .addComponent(rdobca)
                    .addComponent(rdobni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdomandiri)
                    .addComponent(rdobri)
                    .addComponent(rdoovo))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 320, 70));

        jRadioButton24.setBackground(new java.awt.Color(102, 102, 102));
        Gabung2.add(jRadioButton24);
        jRadioButton24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton24.setText("12:00");
        jRadioButton24.setOpaque(false);
        jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 220, 70, -1));

        jRadioButton25.setBackground(new java.awt.Color(102, 102, 102));
        Gabung2.add(jRadioButton25);
        jRadioButton25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton25.setText("15:00");
        jRadioButton25.setOpaque(false);
        jRadioButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 220, 70, -1));

        jRadioButton26.setBackground(new java.awt.Color(102, 102, 102));
        Gabung2.add(jRadioButton26);
        jRadioButton26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton26.setText("18:00");
        jRadioButton26.setOpaque(false);
        jRadioButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton26ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 220, 70, -1));

        jRadioButton27.setBackground(new java.awt.Color(102, 102, 102));
        Gabung2.add(jRadioButton27);
        jRadioButton27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton27.setText("21:00");
        jRadioButton27.setOpaque(false);
        jRadioButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 220, 70, -1));

        jRadioButton28.setBackground(new java.awt.Color(102, 102, 102));
        Gabung3.add(jRadioButton28);
        jRadioButton28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton28.setText("12:00");
        jRadioButton28.setOpaque(false);
        jRadioButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 270, 70, -1));

        jRadioButton29.setBackground(new java.awt.Color(102, 102, 102));
        Gabung3.add(jRadioButton29);
        jRadioButton29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton29.setText("15:00");
        jRadioButton29.setOpaque(false);
        jRadioButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 270, 70, -1));

        jRadioButton30.setBackground(new java.awt.Color(102, 102, 102));
        Gabung3.add(jRadioButton30);
        jRadioButton30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton30.setText("18:00");
        jRadioButton30.setOpaque(false);
        jRadioButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 270, 70, -1));

        jRadioButton31.setBackground(new java.awt.Color(102, 102, 102));
        Gabung3.add(jRadioButton31);
        jRadioButton31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton31.setText("21:00");
        jRadioButton31.setOpaque(false);
        getContentPane().add(jRadioButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 270, 70, -1));

        btnHitung.setBackground(new java.awt.Color(0, 0, 102));
        btnHitung.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung.setMnemonic('H');
        btnHitung.setText("TOTAL");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        btnKosong.setBackground(new java.awt.Color(0, 0, 102));
        btnKosong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKosong.setForeground(new java.awt.Color(255, 255, 255));
        btnKosong.setMnemonic('K');
        btnKosong.setText("ULANGI");
        btnKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongActionPerformed(evt);
            }
        });
        getContentPane().add(btnKosong, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, -1));

        jRadioButton4.setBackground(new java.awt.Color(102, 102, 102));
        Gabung4.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton4.setText("12:00");
        jRadioButton4.setOpaque(false);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 320, 70, -1));

        jRadioButton5.setBackground(new java.awt.Color(102, 102, 102));
        Gabung4.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton5.setText("15:00");
        jRadioButton5.setOpaque(false);
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 320, 70, -1));

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel3.setText("TAYANG SEKARANG");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jRadioButton6.setBackground(new java.awt.Color(102, 102, 102));
        Gabung4.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton6.setText("18:00");
        jRadioButton6.setOpaque(false);
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 320, 70, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("BENTUK PEMBAYARAN ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        chkfilm1.setBackground(new java.awt.Color(102, 102, 102));
        chkfilm1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chkfilm1.setForeground(new java.awt.Color(255, 0, 0));
        chkfilm1.setText("AVENGERS : ENDGAME");
        chkfilm1.setOpaque(false);
        chkfilm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkfilm1ActionPerformed(evt);
            }
        });
        getContentPane().add(chkfilm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jRadioButton7.setBackground(new java.awt.Color(102, 102, 102));
        Gabung4.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton7.setText("21:00");
        jRadioButton7.setOpaque(false);
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 320, 70, -1));

        chkfilm2.setBackground(new java.awt.Color(102, 102, 102));
        chkfilm2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chkfilm2.setForeground(new java.awt.Color(0, 153, 153));
        chkfilm2.setText("TOY STORY 4");
        chkfilm2.setOpaque(false);
        chkfilm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkfilm2ActionPerformed(evt);
            }
        });
        getContentPane().add(chkfilm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Rp. 0");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        chkfilm3.setBackground(new java.awt.Color(102, 102, 102));
        chkfilm3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chkfilm3.setForeground(new java.awt.Color(204, 204, 0));
        chkfilm3.setText("PARASITE");
        chkfilm3.setOpaque(false);
        chkfilm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkfilm3ActionPerformed(evt);
            }
        });
        getContentPane().add(chkfilm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        chkfilm4.setBackground(new java.awt.Color(0, 102, 0));
        chkfilm4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chkfilm4.setForeground(new java.awt.Color(0, 153, 51));
        chkfilm4.setText("JOKER");
        chkfilm4.setOpaque(false);
        chkfilm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkfilm4ActionPerformed(evt);
            }
        });
        getContentPane().add(chkfilm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel7.setText("INFO FILM");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Silakan klik ikon film untuk infromasi lebih lanjut ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        lblJamMenonton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblJamMenonton.setForeground(new java.awt.Color(255, 255, 255));
        lblJamMenonton.setText("Jam Menonton");
        getContentPane().add(lblJamMenonton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIOSKOP STUDIO 20 - BIG SHOT CINEMA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 800, 60));

        txtfilm1.setEditable(false);
        txtfilm1.setBackground(new java.awt.Color(153, 153, 153));
        txtfilm1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtfilm1.setText("0");
        txtfilm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfilm1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtfilm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 60, 40));

        txtfilm2.setEditable(false);
        txtfilm2.setBackground(new java.awt.Color(153, 153, 153));
        txtfilm2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtfilm2.setText("0");
        txtfilm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfilm2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtfilm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 60, 40));

        jRadioButton20.setBackground(new java.awt.Color(102, 102, 102));
        Gabung.add(jRadioButton20);
        jRadioButton20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton20.setText("12:00");
        jRadioButton20.setOpaque(false);
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 170, 70, -1));

        txtfilm3.setEditable(false);
        txtfilm3.setBackground(new java.awt.Color(153, 153, 153));
        txtfilm3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtfilm3.setText("0");
        getContentPane().add(txtfilm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 60, 40));

        jRadioButton21.setBackground(new java.awt.Color(102, 102, 102));
        Gabung.add(jRadioButton21);
        jRadioButton21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton21.setText("15:00");
        jRadioButton21.setOpaque(false);
        getContentPane().add(jRadioButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 170, 70, -1));

        txtfilm4.setEditable(false);
        txtfilm4.setBackground(new java.awt.Color(153, 153, 153));
        txtfilm4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtfilm4.setText("0");
        getContentPane().add(txtfilm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 60, 40));

        jRadioButton22.setBackground(new java.awt.Color(102, 102, 102));
        Gabung.add(jRadioButton22);
        jRadioButton22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton22.setText("18:00");
        jRadioButton22.setOpaque(false);
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 170, 70, -1));

        KlikFilm4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        KlikFilm4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Pictures\\Joker.jpg")); // NOI18N
        KlikFilm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlikFilm4ActionPerformed(evt);
            }
        });
        getContentPane().add(KlikFilm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 80, 120));

        KlikFilm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        KlikFilm.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Pictures\\Avengers_Endgame_poster.jpg")); // NOI18N
        KlikFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlikFilmActionPerformed(evt);
            }
        });
        getContentPane().add(KlikFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 100, 120));

        KlikFilm2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        KlikFilm2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Pictures\\Toy_Story_4_poster.jpg")); // NOI18N
        KlikFilm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlikFilm2ActionPerformed(evt);
            }
        });
        getContentPane().add(KlikFilm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 100, 120));

        KlikFilm3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        KlikFilm3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Pictures\\PArasite.jpg")); // NOI18N
        KlikFilm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlikFilm3ActionPerformed(evt);
            }
        });
        getContentPane().add(KlikFilm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 90, 120));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Harga Tiket ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        lblCaraBayar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCaraBayar1.setForeground(new java.awt.Color(255, 255, 255));
        lblCaraBayar1.setText("Cara Bayar");
        getContentPane().add(lblCaraBayar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, -1, -1));

        jTable2.setBackground(new java.awt.Color(0, 0, 102));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Rp.30.000", "Rp.35.000", "Rp.40.000", "Rp.50.000"}
            },
            new String [] {
                "Avengers Endgame", "Toy Story 4", "Parasite", "Joker"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoscrolls(false);
        jTable2.setOpaque(false);
        jTable2.setSelectionBackground(new java.awt.Color(0, 0, 255));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 290, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\FlatIcon.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    private void rdouangtunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdouangtunaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdouangtunaiActionPerformed

    private void rdomandiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdomandiriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdomandiriActionPerformed

    private void rdoovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoovoActionPerformed

    private void jRadioButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton24ActionPerformed

    private void jRadioButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton26ActionPerformed

    private void jRadioButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton27ActionPerformed

    private void jRadioButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton28ActionPerformed

    private void jRadioButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton29ActionPerformed

    private void jRadioButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton30ActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        boolean lDataOke = true;
        // cek Ada atau tidak :
        // menu dipesan tetapi tidak menuliskan Quantity
        // jika ada, maka variabel lDataOke menjadi false
        if (chkfilm1.isSelected() && " ".equals(txtfilm1.getText()))
        lDataOke = false;
        if (chkfilm2.isSelected() && " ".equals(txtfilm2.getText()))
        lDataOke = false;
        if (chkfilm3.isSelected() && " ".equals(txtfilm3.getText()))
        lDataOke = false;
        if (chkfilm4.isSelected() && " ".equals(txtfilm4.getText()))
        lDataOke = false;
        // jika variabel lDataOke == false, berarti masih ada kesalahan
        // sehingga perlu dimunculkan pesan kesalahan
        if (!lDataOke) {
            javax.swing.JOptionPane.showMessageDialog(null, "Data Dilengkapi dahulu");
        } else {
            // untuk memudahkan, buat variabel baru untuk menampung data
            int nfilm1 = Integer.parseInt(txtfilm1.getText());
            int nfilm2 = Integer.parseInt(txtfilm2.getText());
            int nfilm3 = Integer.parseInt(txtfilm3.getText());
            int nfilm4 = Integer.parseInt(txtfilm4.getText());
            // hitung total
            int nTotal = (30000 * nfilm1)+
            (35000 * nfilm2)+(40000 * nfilm3)+(50000 * nfilm4);
            lblTotal.setText("Rp. "+nTotal);
            // bagian ini untuk menampilkan cara Bayar
            if (rdouangtunai.isSelected())
            lblCaraBayar1.setText(rdouangtunai.getActionCommand());
            if (rdobca.isSelected())
            lblCaraBayar1.setText(rdobca.getActionCommand());
            if (rdobni.isSelected())
            lblCaraBayar1.setText(rdobni.getActionCommand());
            if (rdomandiri.isSelected())
            lblCaraBayar1.setText(rdomandiri.getActionCommand());
            if (rdobri.isSelected())
            lblCaraBayar1.setText(rdobri.getActionCommand());
            if (rdoovo.isSelected())
            lblCaraBayar1.setText(rdoovo.getActionCommand());
            if (jRadioButton20.isSelected())
            lblJamMenonton.setText(jRadioButton20.getActionCommand());
            if (jRadioButton21.isSelected())
            lblJamMenonton.setText(jRadioButton21.getActionCommand());
            if (jRadioButton22.isSelected())
            lblJamMenonton.setText(jRadioButton22.getActionCommand());
            if (jRadioButton23.isSelected())
            lblJamMenonton.setText(jRadioButton23.getActionCommand());
            if (jRadioButton24.isSelected())
            lblJamMenonton.setText(jRadioButton24.getActionCommand());
            if (jRadioButton25.isSelected())
            lblJamMenonton.setText(jRadioButton25.getActionCommand());
            if (jRadioButton26.isSelected())
            lblJamMenonton.setText(jRadioButton26.getActionCommand());
            if (jRadioButton27.isSelected())
            lblJamMenonton.setText(jRadioButton27.getActionCommand());
            if (jRadioButton28.isSelected())
            lblJamMenonton.setText(jRadioButton28.getActionCommand());
            if (jRadioButton29.isSelected())
            lblJamMenonton.setText(jRadioButton29.getActionCommand());
            if (jRadioButton30.isSelected())
            lblJamMenonton.setText(jRadioButton30.getActionCommand());
            if (jRadioButton31.isSelected())
            lblJamMenonton.setText(jRadioButton31.getActionCommand());
            if (jRadioButton4.isSelected())
            lblJamMenonton.setText(jRadioButton4.getActionCommand());
            if (jRadioButton5.isSelected())
            lblJamMenonton.setText(jRadioButton5.getActionCommand());
            if (jRadioButton6.isSelected())
            lblJamMenonton.setText(jRadioButton6.getActionCommand());
            if (jRadioButton7.isSelected())
            lblJamMenonton.setText(jRadioButton7.getActionCommand());
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongActionPerformed
        // TODO add your handling code here:
        chkfilm1.setSelected(false);
        chkfilm2.setSelected(false);
        chkfilm3.setSelected(false);
        chkfilm4.setSelected(false);
        txtfilm1.setText("0");
        txtfilm2.setText("0");
        txtfilm3.setText("0");
        txtfilm4.setText("0");
        txtfilm1.setEditable(false);
        txtfilm2.setEditable(false);
        txtfilm3.setEditable(false);
        txtfilm4.setEditable(false);
        rdouangtunai.setSelected(false);
        rdobca.setSelected(false);
        rdobni.setSelected(false);
        rdobri.setSelected(false);
        rdoovo.setSelected(false);
        rdomandiri.setSelected(false);
        jRadioButton20.setSelected(false);
        jRadioButton21.setSelected(false);
        jRadioButton22.setSelected(false);
        jRadioButton23.setSelected(false);
        jRadioButton24.setSelected(false);
        jRadioButton25.setSelected(false);
        jRadioButton26.setSelected(false);
        jRadioButton27.setSelected(false);
        jRadioButton28.setSelected(false);
        jRadioButton29.setSelected(false);
        jRadioButton30.setSelected(false);
        jRadioButton31.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
        jRadioButton7.setSelected(false);
        lblTotal.setText("Rp. 0");
        lblCaraBayar1.setText("Cara Bayar");
        lblJamMenonton.setText("Jam Menonton");
    }//GEN-LAST:event_btnKosongActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void chkfilm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkfilm1ActionPerformed
        // TODO add your handling code here:
        if (chkfilm1.isSelected()) {
            txtfilm1.setEditable(true);
            txtfilm1.setText("1");
        } else {
            txtfilm1.setEditable(false);
            txtfilm1.setText("0");
        }
    }//GEN-LAST:event_chkfilm1ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void chkfilm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkfilm2ActionPerformed
        // TODO add your handling code here:
        if (chkfilm2.isSelected()) {
            txtfilm2.setEditable(true);
            txtfilm2.setText("1");
        } else {
            txtfilm2.setEditable(false);
            txtfilm2.setText("0");
        }
    }//GEN-LAST:event_chkfilm2ActionPerformed

    private void chkfilm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkfilm3ActionPerformed
        // TODO add your handling code here:
        if (chkfilm3.isSelected()) {
            txtfilm3.setEditable(true);
            txtfilm3.setText("1");
        } else {
            txtfilm3.setEditable(false);
            txtfilm3.setText("0");
        }
    }//GEN-LAST:event_chkfilm3ActionPerformed

    private void chkfilm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkfilm4ActionPerformed
        // TODO add your handling code here:
        if (chkfilm4.isSelected()) {
            txtfilm4.setEditable(true);
            txtfilm4.setText("1");
        } else {
            txtfilm4.setEditable(false);
            txtfilm4.setText("0");
        }
    }//GEN-LAST:event_chkfilm4ActionPerformed

    private void txtfilm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfilm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfilm1ActionPerformed

    private void txtfilm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfilm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfilm2ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton22ActionPerformed

    private void jRadioButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton25ActionPerformed

    private void KlikFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlikFilmActionPerformed
        DescFilm1 d;
        d = new DescFilm1();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KlikFilmActionPerformed

    private void KlikFilm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlikFilm2ActionPerformed
        DescFilm2 e;
        e = new DescFilm2();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KlikFilm2ActionPerformed

    private void KlikFilm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlikFilm3ActionPerformed
        DescFilm3 f;
        f = new DescFilm3();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KlikFilm3ActionPerformed

    private void KlikFilm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlikFilm4ActionPerformed
         DescFilm4 l;
         l = new DescFilm4();
         l.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_KlikFilm4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login1 o= new Login1();
        o.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Gabung;
    private javax.swing.ButtonGroup Gabung2;
    private javax.swing.ButtonGroup Gabung3;
    private javax.swing.ButtonGroup Gabung4;
    private javax.swing.ButtonGroup Gabung5;
    private javax.swing.JButton KlikFilm;
    private javax.swing.JButton KlikFilm2;
    private javax.swing.JButton KlikFilm3;
    private javax.swing.JButton KlikFilm4;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKosong;
    private javax.swing.JCheckBox chkfilm1;
    private javax.swing.JCheckBox chkfilm2;
    private javax.swing.JCheckBox chkfilm3;
    private javax.swing.JCheckBox chkfilm4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCaraBayar1;
    private javax.swing.JLabel lblJamMenonton;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton rdobca;
    private javax.swing.JRadioButton rdobni;
    private javax.swing.JRadioButton rdobri;
    private javax.swing.JRadioButton rdomandiri;
    private javax.swing.JRadioButton rdoovo;
    private javax.swing.JRadioButton rdouangtunai;
    private javax.swing.JTextField txtfilm1;
    private javax.swing.JTextField txtfilm2;
    private javax.swing.JTextField txtfilm3;
    private javax.swing.JTextField txtfilm4;
    // End of variables declaration//GEN-END:variables
}
