/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form1;

/**
 *
 * @author ACER
 */
public class MenuLogin extends javax.swing.JFrame {

    /**
     * Creates new form MenuLogin
     */
    public MenuLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IsiNamaPengguna = new javax.swing.JTextField();
        KonfirmLogin = new javax.swing.JButton();
        IsiPassPengguna = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Big Shot");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 200, 60));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 260, 10));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\video-camera.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 50, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\cinema.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 40, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username  :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Silakan masukan username dan password pengguna");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password   :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        IsiNamaPengguna.setBackground(new java.awt.Color(102, 102, 102));
        IsiNamaPengguna.setForeground(new java.awt.Color(255, 255, 255));
        IsiNamaPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiNamaPenggunaActionPerformed(evt);
            }
        });
        getContentPane().add(IsiNamaPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 156, -1));

        KonfirmLogin.setBackground(new java.awt.Color(153, 153, 255));
        KonfirmLogin.setFont(new java.awt.Font("Nirmala UI", 1, 11)); // NOI18N
        KonfirmLogin.setText("LOGIN");
        KonfirmLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        KonfirmLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KonfirmLoginActionPerformed(evt);
            }
        });
        getContentPane().add(KonfirmLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 110, 30));

        IsiPassPengguna.setBackground(new java.awt.Color(102, 102, 102));
        IsiPassPengguna.setForeground(new java.awt.Color(255, 255, 255));
        IsiPassPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiPassPenggunaActionPerformed(evt);
            }
        });
        getContentPane().add(IsiPassPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 155, -1));

        jLabel9.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cinema");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 170, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\user.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\password.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\FlatIcon.png")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IsiNamaPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiNamaPenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiNamaPenggunaActionPerformed

    private void KonfirmLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KonfirmLoginActionPerformed
        String username = "Abryp";
        String password = "H1051191034";
        if(username.equalsIgnoreCase(IsiNamaPengguna.getText()) && password.equalsIgnoreCase(IsiPassPengguna.getText())) {
            this.setVisible(false);
            new MenuUtama().setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Maaf Username dan password yang dimasukan salah!");
            IsiNamaPengguna.setText("");
            IsiPassPengguna.setText("");
            IsiNamaPengguna.requestFocus();
        }
    }//GEN-LAST:event_KonfirmLoginActionPerformed

    private void IsiPassPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiPassPenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiPassPenggunaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IsiNamaPengguna;
    private javax.swing.JPasswordField IsiPassPengguna;
    private javax.swing.JButton KonfirmLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
